function [BW,maskedImage] = segmentImage(RGB)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 10-Jan-2019
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Graph cut
foregroundInd = [9206415 9322415 10526415 10702415 10842444 11274516 11534588 11734645 11822667 11878674 12078731 12222753 12366760 12598774 12882774 13258753 13514717 13686674 13774631 13802616 ];
backgroundInd = [7542121 7542150 7542193 7570236 7570257 7598071 7654308 7742006 7798379 7969956 8030444 8201920 8258537 8457891 8834695 8861862 9177848 9782925 9809834 10153812 10559105 10615097 10641798 10731119 10759112 10759119 10787119 10875126 11047133 11157783 11303141 11507148 11677769 11679162 12079169 12105755 12565755 12739191 12969755 13197762 13541769 13543212 13685776 14001805 14235227 14261841 14405862 14491227 14549877 14635205 14693905 14921948 15181999 15211083 15326042 15410085 15470997 15526128 15614185 15642896 15698315 15726796 15786437 15786602 15786681 ];
L = superpixels(X,120100,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = lazysnapping(scaledX,L,foregroundInd,backgroundInd);

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

function out = prepLab(in)

% Convert L*a*b* image to range [0,1]
out = in;
out(:,:,1)   = in(:,:,1) / 100;  % L range is [0 100].
out(:,:,2:3) = (in(:,:,2:3) + 100) / 200;  % a* and b* range is [-100,100].

end
