function [BW,maskedImage] = createMaskApple(RGB)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 01-Mar-2019
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Graph cut
foregroundInd = [10629724 10629737 10645679 10645751 10645755 10681657 10681764 10701639 10737603 10753778 10773563 10773572 10773778 10809782 10825778 10861782 10881782 10917518 10949796 10969800 11057473 11237424 11257419 11257840 11417863 11433397 11561876 11649379 11685890 11757370 11777899 11917903 11989912 12061917 12081357 12133361 12169930 12277934 12329361 12385939 12437370 12473934 12529930 12545379 12545925 12617908 12637903 12653397 12669397 12797424 12849849 12869827 12885437 12921455 12941460 12977764 12993755 13013733 13029491 13049509 13049657 13049675 13049697 13065527 13065540 13065563 13065581 13065603 13065612 ];
backgroundInd = [10269809 10609885 10717912 10773925 10789934 10809939 10845943 10897957 10933966 10949970 10969979 11021988 11113997 11129997 ];
L = superpixels(X,120100,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = lazysnapping(scaledX,L,foregroundInd,backgroundInd);

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

function out = prepLab(in)

% Convert L*a*b* image to range [0,1]
out = in;
out(:,:,1)   = in(:,:,1) / 100;  % L range is [0 100].
out(:,:,2:3) = (in(:,:,2:3) + 100) / 200;  % a* and b* range is [-100,100].

end
